### ISSUE TITLE
vePOP & Total vePOP Rewards sections need adjusting

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/gauges#10]
1. Buttons on vePOP card should have copu on the same line. Please reduce font size.
2. vePOP and Total vePOP Rewards cards are not same dimensions. See snapshot.

<img width="1065" alt="Screenshot 2023-08-16 at 11 13 19 AM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/22d30dca-4a15-4910-a31a-6233d982a556">

**Comment by RedVeil** [comment]
i moved the get Pop button into the actual modals
