### ISSUE TITLE
Exercising oPOP wallet amount

### ISSUE THREAD

**Issue by alec-pop** [Popcorn-Limited/gauges#25]
Need to manually input oPOP exercise amount. Would be great to preview the amount of oPOP already in wallet with a 'Max' button
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/ac585ff4-2576-44c7-940a-6bc2de39b715)

**Comment by amatureApe** [comment]
This has already been added and waiting to be merged to the working vePOP deployment
