### ISSUE TITLE
oPOP claim error

### ISSUE THREAD

**Issue by alec-pop** [Popcorn-Limited/gauges#26]
When I click to claim oPOP and X out of the metamask window I get this error:
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/97b4b6d8-3b95-405f-8cec-0eaf16628498)

**Comment by amatureApe** [comment]
This unfortunately I'm unable to reproduce as I don't have any claim to oPOP this epoch due to the staking yield share issue discussed yesterday. It works well with V2 contracts though. Will have to see
