### ISSUE TITLE
Smart Vault TVL calculation

### ISSUE THREAD

**Issue by alec-pop** [Popcorn-Limited/gauges#28]
20K POP reading as $20K TVL. Not sure if this is a testnet configuration or if vault is not properly pricing the POP tokens
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/85148de5-cf37-415b-bb17-2ef9fe0431ad)

**Comment by amatureApe** [comment]
This we will have to wait until Mainnet because prices are all bad on Goerli
