### ISSUE TITLE
Unlocked vePOP still projects voting power

### ISSUE THREAD

**Issue by alec-pop** [Popcorn-Limited/gauges#33]
I unlocked my vePOP during the current voting cycle and it still shows that the gauge I voted for has a 100% weight in the current cycle and 95.29% of the next vote. Should these not revert to 0?
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/aaa1e742-6a86-44ca-a325-0cb69876d9ed)

**Comment by amatureApe** [comment]
This is by design in the contracts. Your votes are still set regardless of whether you decide to unlock your vote or not. The data here will look better when more users with real value are voting.
