### ISSUE TITLE
Voting issues

### ISSUE THREAD

**Issue by alec-pop** [Popcorn-Limited/gauges#37]
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/8d722abc-33b1-41eb-91c8-5a6cac01b367)
![image](https://github.com/Popcorn-Limited/gauges/assets/113189499/73b3a2f4-fabb-4889-88cb-2dec8f6f5a36)

Few issues
- Vote % shows up as '0%' or 'NaN %'
- Voting is grayed out although My Votes is 0 and I have not recently voted
- APR shows up as 2132233.2361454037 %
- Michael's My Votes is well over 100%
- Not entirely clear what the difference in current v upcoming v my vote columns. May be helpful to add more copy explaining

**Comment by amatureApe** [comment]
1. Can fix that
2. That's a recent change Leon made. Will coordinate with him
3. That should be right as we are depositing a ton of ETH as rewards and the price of POP is only $0.03. It should even out on mainnet with real numbers
4. Will look into this
5. Yes maybe a tooltip would be useful here
