### ISSUE TITLE
Lock your POP calculation shows negative "New Voting power"

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/gauges#4]
When adding more POP to your lock time, "new voting power" reads negative

<img width="504" alt="Screenshot 2023-08-15 at 11 00 12 AM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/9ce257ae-16e7-41df-b03c-69d808037081">

**Comment by RedVeil** [comment]
fixed
