### ISSUE TITLE
Missing information on VePOP rewards & Gauge cards

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/gauges#6]
The gauge card should include the following information:

- Current period votes
- oPOP weekly emissions

Total vePOP rewards is missing

- WETH
- information button for both APR

<img width="665" alt="Screenshot 2023-08-15 at 1 00 24 PM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/bbd93c78-8798-4e39-a402-5ef007ebf7e4">

<img width="1284" alt="Screenshot 2023-08-15 at 1 01 08 PM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/bbb1b87a-89a6-4332-ab7a-9f916ed4d417">

**Comment by RedVeil** [comment]
@amatureApe I already did the current period votes here. id say oPOP weekly emissions is smth we can leave out at the moment and in later.

**Comment by RedVeil** [comment]
@amatureApe The apy part of this ticket is smth that we should tackle though. We need to figure out and add the following:
1. How to fund the vePOP contract with rewards
2. How to calculate the apy
3. How to claim
4. Add apy data to the card
5. Add a claim button

**Comment by RedVeil** [comment]
Ruhum already checked out most of that if any questions arise

**Comment by amatureApe** [comment]
Ok sounds good
