### ISSUE TITLE
Banner area dimensions and area needs to be reduced 75%

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/gauges#9]
This sections takes up too much space on Macbook 13" as well as Samsung Wide Screen. Please use bunni.pro as reference.

<img width="1277" alt="Screenshot 2023-08-16 at 11 10 20 AM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/ddc1fa62-0fae-4882-9f8b-418adcb0f347">

<img width="1275" alt="Screenshot 2023-08-16 at 11 12 04 AM" src="https://github.com/Popcorn-Limited/gauges/assets/88731911/2dd05e19-9f41-4798-8c05-e7b76b85f8bb">

**Comment by enialoleon** [comment]
Here is the link for design: https://www.figma.com/file/rnPQlbFW732rZJS1xEQ167/Popcorn-Dapp?type=design&node-id=16011%3A85524&mode=design&t=MblrWScGQlSFVQdu-1

Use the same margin, padding, font size etc. 
<img width="1439" alt="Screenshot 2023-08-22 at 10 56 22" src="https://github.com/Popcorn-Limited/gauges/assets/123659132/dbc85624-b463-46f2-ac5f-02fe37dfa702">

**Comment by amatureApe** [comment]
Ah gotcha. Sounds good.
